export enum GamePhase {
  LOGIC_PARALLEL = 0,
  LOGIC_SEQUENTIAL = 1,
  PHYSICS_PARALLEL = 2,
  PHYSICS_SEQUENTIAL = 3,
  COLLISION_PARALLEL = 4,
  COLLISION_SEQUENTIAL = 5,
  RENDER_PARALLEL = 6,
  RENDER_SEQUENTIAL = 7,
}
