export enum GamePhase {
  LOGIC_PARALLEL = 0,
  LOGIC_SEQUENTIAL = 1,
  CPU_TO_GPU_DATA_SYNC = 2,
  PHYSICS_PARALLEL = 3,
  PHYSICS_SEQUENTIAL = 4,
  COLLISION_PARALLEL = 5,
  COLLISION_SEQUENTIAL = 6,
  RENDER_PARALLEL = 7,
  RENDER_SEQUENTIAL = 8,
  GPU_TO_CPU_DATA_SYNC = 9,
}
